// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: pkg/shared/protobuff/core-menu.proto

package core_menu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamsCoreMenu int32

const (
	StreamsCoreMenu_SyncMenu StreamsCoreMenu = 0
)

// Enum value maps for StreamsCoreMenu.
var (
	StreamsCoreMenu_name = map[int32]string{
		0: "SyncMenu",
	}
	StreamsCoreMenu_value = map[string]int32{
		"SyncMenu": 0,
	}
)

func (x StreamsCoreMenu) Enum() *StreamsCoreMenu {
	p := new(StreamsCoreMenu)
	*p = x
	return p
}

func (x StreamsCoreMenu) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamsCoreMenu) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_shared_protobuff_core_menu_proto_enumTypes[0].Descriptor()
}

func (StreamsCoreMenu) Type() protoreflect.EnumType {
	return &file_pkg_shared_protobuff_core_menu_proto_enumTypes[0]
}

func (x StreamsCoreMenu) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamsCoreMenu.Descriptor instead.
func (StreamsCoreMenu) EnumDescriptor() ([]byte, []int) {
	return file_pkg_shared_protobuff_core_menu_proto_rawDescGZIP(), []int{0}
}

type StreamsCoreMenuSubjects int32

const (
	StreamsCoreMenuSubjects_GetMenuLegacy StreamsCoreMenuSubjects = 0
)

// Enum value maps for StreamsCoreMenuSubjects.
var (
	StreamsCoreMenuSubjects_name = map[int32]string{
		0: "GetMenuLegacy",
	}
	StreamsCoreMenuSubjects_value = map[string]int32{
		"GetMenuLegacy": 0,
	}
)

func (x StreamsCoreMenuSubjects) Enum() *StreamsCoreMenuSubjects {
	p := new(StreamsCoreMenuSubjects)
	*p = x
	return p
}

func (x StreamsCoreMenuSubjects) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamsCoreMenuSubjects) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_shared_protobuff_core_menu_proto_enumTypes[1].Descriptor()
}

func (StreamsCoreMenuSubjects) Type() protoreflect.EnumType {
	return &file_pkg_shared_protobuff_core_menu_proto_enumTypes[1]
}

func (x StreamsCoreMenuSubjects) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamsCoreMenuSubjects.Descriptor instead.
func (StreamsCoreMenuSubjects) EnumDescriptor() ([]byte, []int) {
	return file_pkg_shared_protobuff_core_menu_proto_rawDescGZIP(), []int{1}
}

var File_pkg_shared_protobuff_core_menu_proto protoreflect.FileDescriptor

var file_pkg_shared_protobuff_core_menu_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2d, 0x6d, 0x65, 0x6e, 0x75,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x75,
	0x2a, 0x1f, 0x0a, 0x0f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x43, 0x6f, 0x72, 0x65, 0x4d,
	0x65, 0x6e, 0x75, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x4d, 0x65, 0x6e, 0x75, 0x10,
	0x00, 0x2a, 0x2c, 0x0a, 0x17, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x43, 0x6f, 0x72, 0x65,
	0x4d, 0x65, 0x6e, 0x75, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x11, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x4c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x10, 0x00, 0x42,
	0x20, 0x5a, 0x1e, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2d, 0x6d, 0x65, 0x6e,
	0x75, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_shared_protobuff_core_menu_proto_rawDescOnce sync.Once
	file_pkg_shared_protobuff_core_menu_proto_rawDescData = file_pkg_shared_protobuff_core_menu_proto_rawDesc
)

func file_pkg_shared_protobuff_core_menu_proto_rawDescGZIP() []byte {
	file_pkg_shared_protobuff_core_menu_proto_rawDescOnce.Do(func() {
		file_pkg_shared_protobuff_core_menu_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_shared_protobuff_core_menu_proto_rawDescData)
	})
	return file_pkg_shared_protobuff_core_menu_proto_rawDescData
}

var file_pkg_shared_protobuff_core_menu_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_shared_protobuff_core_menu_proto_goTypes = []interface{}{
	(StreamsCoreMenu)(0),         // 0: coremenu.StreamsCoreMenu
	(StreamsCoreMenuSubjects)(0), // 1: coremenu.StreamsCoreMenuSubjects
}
var file_pkg_shared_protobuff_core_menu_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_shared_protobuff_core_menu_proto_init() }
func file_pkg_shared_protobuff_core_menu_proto_init() {
	if File_pkg_shared_protobuff_core_menu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_shared_protobuff_core_menu_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_shared_protobuff_core_menu_proto_goTypes,
		DependencyIndexes: file_pkg_shared_protobuff_core_menu_proto_depIdxs,
		EnumInfos:         file_pkg_shared_protobuff_core_menu_proto_enumTypes,
	}.Build()
	File_pkg_shared_protobuff_core_menu_proto = out.File
	file_pkg_shared_protobuff_core_menu_proto_rawDesc = nil
	file_pkg_shared_protobuff_core_menu_proto_goTypes = nil
	file_pkg_shared_protobuff_core_menu_proto_depIdxs = nil
}
