// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: pkg/shared/protobuff/menu.proto

package menu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandMenu int32

const (
	CommandMenu_UpdateAll         CommandMenu = 0
	CommandMenu_UpdateRestaurants CommandMenu = 1
	CommandMenu_UpdateChains      CommandMenu = 2
)

// Enum value maps for CommandMenu.
var (
	CommandMenu_name = map[int32]string{
		0: "UpdateAll",
		1: "UpdateRestaurants",
		2: "UpdateChains",
	}
	CommandMenu_value = map[string]int32{
		"UpdateAll":         0,
		"UpdateRestaurants": 1,
		"UpdateChains":      2,
	}
)

func (x CommandMenu) Enum() *CommandMenu {
	p := new(CommandMenu)
	*p = x
	return p
}

func (x CommandMenu) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandMenu) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_shared_protobuff_menu_proto_enumTypes[0].Descriptor()
}

func (CommandMenu) Type() protoreflect.EnumType {
	return &file_pkg_shared_protobuff_menu_proto_enumTypes[0]
}

func (x CommandMenu) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandMenu.Descriptor instead.
func (CommandMenu) EnumDescriptor() ([]byte, []int) {
	return file_pkg_shared_protobuff_menu_proto_rawDescGZIP(), []int{0}
}

type Entity int32

const (
	Entity_Products Entity = 0
	Entity_Menu     Entity = 1
)

// Enum value maps for Entity.
var (
	Entity_name = map[int32]string{
		0: "Products",
		1: "Menu",
	}
	Entity_value = map[string]int32{
		"Products": 0,
		"Menu":     1,
	}
)

func (x Entity) Enum() *Entity {
	p := new(Entity)
	*p = x
	return p
}

func (x Entity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Entity) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_shared_protobuff_menu_proto_enumTypes[1].Descriptor()
}

func (Entity) Type() protoreflect.EnumType {
	return &file_pkg_shared_protobuff_menu_proto_enumTypes[1]
}

func (x Entity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Entity.Descriptor instead.
func (Entity) EnumDescriptor() ([]byte, []int) {
	return file_pkg_shared_protobuff_menu_proto_rawDescGZIP(), []int{1}
}

type Store struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ChainId   uint32 `protobuf:"varint,3,opt,name=chainId,proto3" json:"chainId,omitempty"`
	ChainName string `protobuf:"bytes,4,opt,name=chainName,proto3" json:"chainName,omitempty"`
}

func (x *Store) Reset() {
	*x = Store{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_shared_protobuff_menu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_shared_protobuff_menu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_pkg_shared_protobuff_menu_proto_rawDescGZIP(), []int{0}
}

func (x *Store) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Store) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Store) GetChainId() uint32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *Store) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stores []*Store `protobuf:"bytes,1,rep,name=stores,proto3" json:"stores,omitempty"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_shared_protobuff_menu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_shared_protobuff_menu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_pkg_shared_protobuff_menu_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetStores() []*Store {
	if x != nil {
		return x.Stores
	}
	return nil
}

type SendMenu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload  string      `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Command  CommandMenu `protobuf:"varint,3,opt,name=command,proto3,enum=menu.CommandMenu" json:"command,omitempty"`
	Entity   Entity      `protobuf:"varint,4,opt,name=entity,proto3,enum=menu.Entity" json:"entity,omitempty"`
	Metadata *Metadata   `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *SendMenu) Reset() {
	*x = SendMenu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_shared_protobuff_menu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMenu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMenu) ProtoMessage() {}

func (x *SendMenu) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_shared_protobuff_menu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMenu.ProtoReflect.Descriptor instead.
func (*SendMenu) Descriptor() ([]byte, []int) {
	return file_pkg_shared_protobuff_menu_proto_rawDescGZIP(), []int{2}
}

func (x *SendMenu) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SendMenu) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *SendMenu) GetCommand() CommandMenu {
	if x != nil {
		return x.Command
	}
	return CommandMenu_UpdateAll
}

func (x *SendMenu) GetEntity() Entity {
	if x != nil {
		return x.Entity
	}
	return Entity_Products
}

func (x *SendMenu) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_pkg_shared_protobuff_menu_proto protoreflect.FileDescriptor

var file_pkg_shared_protobuff_menu_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x2f, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6d, 0x65, 0x6e, 0x75, 0x22, 0x63, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x08,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x23, 0x0a, 0x06, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x06, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x22, 0xb3, 0x01,
	0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2b, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x12, 0x24, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0c, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52,
	0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x2a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x65, 0x6e, 0x75,
	0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x2a, 0x45, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4d, 0x65,
	0x6e, 0x75, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x10,
	0x00, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x74, 0x61,
	0x75, 0x72, 0x61, 0x6e, 0x74, 0x73, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x10, 0x02, 0x2a, 0x20, 0x0a, 0x06, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x65, 0x6e, 0x75, 0x10, 0x01, 0x42, 0x1c, 0x5a, 0x1a,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x66, 0x2f, 0x6d, 0x65, 0x6e, 0x75, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_shared_protobuff_menu_proto_rawDescOnce sync.Once
	file_pkg_shared_protobuff_menu_proto_rawDescData = file_pkg_shared_protobuff_menu_proto_rawDesc
)

func file_pkg_shared_protobuff_menu_proto_rawDescGZIP() []byte {
	file_pkg_shared_protobuff_menu_proto_rawDescOnce.Do(func() {
		file_pkg_shared_protobuff_menu_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_shared_protobuff_menu_proto_rawDescData)
	})
	return file_pkg_shared_protobuff_menu_proto_rawDescData
}

var file_pkg_shared_protobuff_menu_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_shared_protobuff_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_shared_protobuff_menu_proto_goTypes = []interface{}{
	(CommandMenu)(0), // 0: menu.CommandMenu
	(Entity)(0),      // 1: menu.Entity
	(*Store)(nil),    // 2: menu.Store
	(*Metadata)(nil), // 3: menu.Metadata
	(*SendMenu)(nil), // 4: menu.SendMenu
}
var file_pkg_shared_protobuff_menu_proto_depIdxs = []int32{
	2, // 0: menu.Metadata.stores:type_name -> menu.Store
	0, // 1: menu.SendMenu.command:type_name -> menu.CommandMenu
	1, // 2: menu.SendMenu.entity:type_name -> menu.Entity
	3, // 3: menu.SendMenu.metadata:type_name -> menu.Metadata
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_shared_protobuff_menu_proto_init() }
func file_pkg_shared_protobuff_menu_proto_init() {
	if File_pkg_shared_protobuff_menu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_shared_protobuff_menu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Store); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_shared_protobuff_menu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_shared_protobuff_menu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMenu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_shared_protobuff_menu_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_shared_protobuff_menu_proto_goTypes,
		DependencyIndexes: file_pkg_shared_protobuff_menu_proto_depIdxs,
		EnumInfos:         file_pkg_shared_protobuff_menu_proto_enumTypes,
		MessageInfos:      file_pkg_shared_protobuff_menu_proto_msgTypes,
	}.Build()
	File_pkg_shared_protobuff_menu_proto = out.File
	file_pkg_shared_protobuff_menu_proto_rawDesc = nil
	file_pkg_shared_protobuff_menu_proto_goTypes = nil
	file_pkg_shared_protobuff_menu_proto_depIdxs = nil
}
